# Generated by Django 6.0.1 on 2026-02-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(max_length=11)),
                ('rg', models.IntegerField(max_length=20)),
                ('nome', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=15)),
                ('idade', models.IntegerField(max_length=3)),
                ('telefone', models.IntegerField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('dt_nascimento', models.DateField()),
                ('cep', models.IntegerField(max_length=8)),
                ('endereco', models.CharField(max_length=20)),
                ('complemento', models.TextField(max_length=60)),
                ('status', models.BooleanField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
