# Generated by Django 6.0.1 on 2026-02-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
