# Generated by Django 6.0.1 on 2026-02-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pessoa_cep_alter_pessoa_cpf_alter_pessoa_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='Categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='Equipamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipamento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='Pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pessoa'),
        ),
    ]
